services:
  db:
    image: postgres:14-alpine
    container_name: dockdb
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=trust"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 4s
      timeout: 6s
      retries: 2

  opa:
    image: openpolicyagent/opa:0.1.1-dev
    container_name: dockops_opa
    ports:
      - "8181:8181"
    command: ["run", "--server", "--log-level=debug", "/policies"]
    volumes:
      - ./policies:/policies
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${userRbMQ}
      RABBITMQ_DEFAULT_PASS: ${passRbMq}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 10s
      retries: 5
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq

  app:
    build: .
    container_name: dockOps-API
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DB_URL: "host=dockdb user=${DB_USER} password=${DB_PASSWORD} dbname=${DB_NAME} port=5432 sslmode=disable"
      JWT_SECRET: ${SECRET_KEY_JWT}
      OPA_URL: "http://opa:8181/v1/data/dockops/authz/allow"
    ports:
      - "8080:8080"

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."

volumes:
  postgres_data:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local
